const tracks=[
 {id:1,title:'Midnight City',artist:'M83',album:'Hurry Up, We’re Dreaming',time:'4:03',cover:'gradient-1',src:'https://cdn.pixabay.com/audio/2022/10/25/audio_9468e2c2a6.mp3'},
 {id:2,title:'A Moment Apart',artist:'ODESZA',album:'A Moment Apart',time:'3:54',cover:'gradient-2',src:'https://cdn.pixabay.com/audio/2023/04/24/audio_35b8cd5e9d.mp3'},
 {id:3,title:'Sunset Lover',artist:'Petit Biscuit',album:'Presence',time:'3:58',cover:'gradient-3',src:'https://cdn.pixabay.com/audio/2022/05/27/audio_1808fbf07a.mp3'},
 {id:4,title:'Innerbloom',artist:'RÜFÜS DU SOL',album:'Bloom',time:'9:35',cover:'gradient-4',src:'https://cdn.pixabay.com/audio/2022/03/15/audio_2c8b2c3a62.mp3'},
 {id:5,title:'The Less I Know The Better',artist:'Tame Impala',album:'Currents',time:'3:36',cover:'gradient-5',src:'https://cdn.pixabay.com/audio/2022/02/23/audio_8b5f4f2c64.mp3'},
 {id:6,title:'Nightcall',artist:'Kavinsky',album:'OutRun',time:'4:18',cover:'gradient-6',src:'https://cdn.pixabay.com/audio/2022/08/23/audio_1b7b9c7e2b.mp3'},
 {id:7,title:'Electric Feel',artist:'MGMT',album:'Oracular Spectacular',time:'3:49',cover:'gradient-7',src:'https://cdn.pixabay.com/audio/2022/10/30/audio_5c8e1a0bb5.mp3'}
];
const audio=document.querySelector('#audio'), view=document.querySelector('#view'), input=document.querySelector('#searchInput');
let liked=JSON.parse(localStorage.getItem('vibe-liked')||'[]'), queue=[...tracks], current=null, isShuffle=false, isRepeat=false;
const $=s=>document.querySelector(s); const fmt=s=>{if(!s||Number.isNaN(s))return'0:00';return `${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`};
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2400)}
function cover(t,small=false){return `<div class="${small?'track-cover':'cover'} ${t.cover}">✦${small?'':''}${!small?`<button class="play-float" data-play="${t.id}" aria-label="Воспроизвести">▶</button>`:''}</div>`}
function trackRow(t,i){return `<div class="track"><span class="track-num">${String(i+1).padStart(2,'0')}</span>${cover(t,true)}<button class="track-info" data-play="${t.id}" style="text-align:left"><div class="track-name">${t.title}</div><div class="track-author">${t.artist} · ${t.album}</div></button><span class="track-time">${t.time}</span><button class="track-like ${liked.includes(t.id)?'liked':''}" data-like="${t.id}" aria-label="Любимое">${liked.includes(t.id)?'♥':'♡'}</button></div>`}
function cards(list){return `<div class="cards">${list.map(t=>`<article class="card">${cover(t)}<div class="card-title">${t.title}</div><div class="card-subtitle">${t.artist}</div></article>`).join('')}</div>`}
function renderDiscover(){view.innerHTML=`<section class="hero"><div><div class="eyebrow">Среда, 7 октября</div><h1>Музыка для<br><span style="color:var(--accent)">твоего момента.</span></h1><p>Твой звук. Твои правила. Твой вайб.</p></div></section><section class="section"><div class="section-head"><h2>Слушай прямо сейчас</h2><button class="see-all">Обновить подборку ↗</button></div>${cards(tracks.slice(0,5))}</section><section class="section"><div class="section-head"><h2>Персональные миксы</h2><button class="see-all">Смотреть все →</button></div><div class="cards">${[['Вечерний вайб','Для спокойного вечера','mix-1'],['Фокус и поток','Музыка для концентрации','mix-2'],['На полной громкости','Твой заряд на сегодня','mix-3']].map(x=>`<div class="mix-card ${x[2]}"><strong>${x[0]}</strong><small>${x[1]}</small></div>`).join('')}</div></section><section class="section"><div class="section-head"><h2>Популярное сегодня</h2><button class="see-all">Весь чарт →</button></div><div class="track-list">${tracks.slice(0,5).map(trackRow).join('')}</div></section>`;bind();}
function renderSearch(q=''){const found=tracks.filter(t=>(t.title+' '+t.artist+' '+t.album).toLowerCase().includes(q.toLowerCase()));view.innerHTML=`<section class="hero"><div><div class="eyebrow">Поиск</div><h1>${q?`Результаты для<br><span style="color:var(--accent)">«${q}»</span>`:'Найди свой следующий трек.'}</h1></div></section><section class="section">${found.length?`<div class="track-list">${found.map(trackRow).join('')}</div>`:'<div class="empty"><strong>Ничего не нашли</strong>Попробуй другое название, исполнителя или альбом.</div>'}</section>`;bind()}
function renderLibrary(mode='library'){let list=mode==='liked'?tracks.filter(t=>liked.includes(t.id)):queue;view.innerHTML=`<section class="hero"><div><div class="eyebrow">Твоя коллекция</div><h1>${mode==='liked'?'Любимые треки':'Моя музыка'}</h1><p>${list.length} ${list.length===1?'трек':'треков'} в коллекции</p></div></section><section class="section">${list.length?`<div class="track-list">${list.map(trackRow).join('')}</div>`:`<div class="empty"><strong>Здесь пока пусто</strong>Нажимай ♡ у треков, чтобы собрать свою коллекцию.</div>`}</section>`;bind()}
function renderImports(){view.innerHTML=`<section class="hero"><div><div class="eyebrow">Твоя музыка</div><h1>Добавь музыку<br><span style="color:var(--accent)">из любого места.</span></h1><p>Собери всё любимое в одном красивом плеере.</p></div></section><section class="section"><div class="import-grid"><article class="import-card"><div class="import-icon">↥</div><h3>Файлы с устройства</h3><p>MP3, WAV, FLAC и другие форматы. Файлы останутся только у тебя.</p><button id="fileBtn">Выбрать файлы</button><input id="fileInput" type="file" accept="audio/*" multiple hidden></article><article class="import-card"><div class="import-icon">◉</div><h3>Ссылка на трек</h3><p>Вставь прямую ссылку на аудиофайл — и добавь его в очередь.</p><button id="urlBtn">Добавить ссылку</button></article><article class="import-card"><div class="import-icon">↔</div><h3>Перенести коллекцию</h3><p>Импортируй плейлисты из других сервисов через CSV-файл.</p><button id="csvBtn">Импортировать CSV</button><input id="csvInput" type="file" accept=".csv" hidden></article></div></section>`;$('#fileBtn').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>{[...e.target.files].forEach(f=>queue.push({id:Date.now()+Math.random(),title:f.name.replace(/\.[^.]+$/,''),artist:'Локальный файл',album:'Моя музыка',time:'—',cover:'gradient-7',src:URL.createObjectURL(f)}));updateCounts();toast('Файлы добавлены в твою музыку')};$('#urlBtn').onclick=()=>{const url=prompt('Вставь прямую ссылку на аудиофайл (MP3, WAV или OGG):');if(url&&/^https?:\/\//i.test(url)){queue.push({id:Date.now(),title:'Трек по ссылке',artist:'Добавленный источник',album:'Моя музыка',time:'—',cover:'gradient-2',src:url});updateCounts();toast('Ссылка добавлена в очередь')}else if(url)toast('Нужна корректная ссылка http:// или https://')};$('#csvBtn').onclick=()=>$('#csvInput').click();$('#csvInput').onchange=()=>toast('CSV выбран. Импорт формата будет доступен в следующем обновлении')}
function updateCounts(){$('#likedCount').textContent=liked.length;$('#queueCount').textContent=queue.length}
function play(id){const t=tracks.find(x=>x.id==id)||queue.find(x=>x.id==id);if(!t)return;current=t;audio.src=t.src;audio.play().catch(()=>toast('Нажми Play ещё раз, чтобы начать воспроизведение'));$('#playerTitle').textContent=t.title;$('#playerArtist').textContent=t.artist;$('#playerCover').className=`mini-cover ${t.cover}`;$('#playerLike').classList.toggle('liked',liked.includes(t.id));$('#playerLike').textContent=liked.includes(t.id)?'♥':'♡';$('#playBtn').textContent='Ⅱ'}
function bind(){document.querySelectorAll('[data-play]').forEach(x=>x.onclick=()=>play(x.dataset.play));document.querySelectorAll('[data-like]').forEach(x=>x.onclick=()=>{const id=Number(x.dataset.like);liked=liked.includes(id)?liked.filter(v=>v!==id):[...liked,id];localStorage.setItem('vibe-liked',JSON.stringify(liked));updateCounts();const hash=location.hash.slice(1);if(hash==='liked')renderLibrary('liked');else x.classList.toggle('liked');x.textContent=liked.includes(id)?'♥':'♡';$('#playerLike').classList.toggle('liked',current&&liked.includes(current.id))})}
function route(){const h=location.hash.slice(1)||'discover';document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===h));if(h==='search')renderSearch(input.value);else if(h==='liked')renderLibrary('liked');else if(h==='library'||h==='queue')renderLibrary();else if(h==='imports')renderImports();else renderDiscover()}
input.oninput=()=>{if(location.hash!=='#search')location.hash='search';renderSearch(input.value)};window.onhashchange=route;$('#playBtn').onclick=()=>{if(!current)play(queue[0].id);else if(audio.paused){audio.play();$('#playBtn').textContent='Ⅱ'}else{audio.pause();$('#playBtn').textContent='▶'}};$('#nextBtn').onclick=()=>{const i=queue.findIndex(t=>t.id===current?.id);play(queue[(i+1)%queue.length].id)};$('#prevBtn').onclick=()=>{const i=queue.findIndex(t=>t.id===current?.id);play(queue[(i-1+queue.length)%queue.length].id)};$('#shuffleBtn').onclick=()=>{isShuffle=!isShuffle;toast(isShuffle?'Перемешивание включено':'Перемешивание выключено')};$('#repeatBtn').onclick=()=>{isRepeat=!isRepeat;audio.loop=isRepeat;toast(isRepeat?'Повтор включён':'Повтор выключен')};$('#volume').oninput=e=>audio.volume=e.target.value;audio.ontimeupdate=()=>{$('#progress').value=audio.duration?audio.currentTime/audio.duration*100:0;$('#currentTime').textContent=fmt(audio.currentTime);$('#duration').textContent=fmt(audio.duration)};$('#progress').oninput=e=>{if(audio.duration)audio.currentTime=e.target.value/100*audio.duration};audio.onended=()=>{if(!isRepeat)$('#nextBtn').click()};$('#playerLike').onclick=()=>{if(current){const el=document.querySelector(`[data-like="${current.id}"]`);el?.click();$('#playerLike').classList.toggle('liked',liked.includes(current.id))}};$('#queueBtn').onclick=()=>location.hash='queue';$('.mobile-menu').onclick=()=>$('.sidebar').classList.toggle('open');document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();input.focus()}});updateCounts();route();
